---
- hosts: "{{ cd_env }}"
#  vars:
#    - jar_file: "{{ packer }}.jar"
  tasks:

    - name: check work path
      stat: path=/home/admin/ops_screen
      register: work_path

    - name: create work path
      file: path=/home/admin/ops_screen state=directory
      when: work_path.stat.isdir is not defined

    - name: check run path
      stat: path=/home/admin/ops_screen/run
      register: work_run_path

    - name: create work run path
      file: path=/home/admin/ops_screen/run state=directory
      when: work_run_path.stat.isdir is not defined

    - name: check logs path
      stat: path=/home/admin/ops_screen/logs
      register: work_logs_path

    - name: create work logs path
      file: path=/home/admin/ops_screen/logs state=directory
      when: work_logs_path.stat.isdir is not defined

    - name: check logs path
      stat: path=/home/admin/ops_screen/dist/index.html
      register: work_index_file

    - name: archive work path
      archive: path=/home/admin/ops_screen/dist/* dest=/home/admin/ops_screen/bak.tgz remove=True
      when: work_index_file.stat.isdir is defined

    - name: copy packer
      copy: src={{project}}/dist dest=/home/admin/ops_screen

#    - name: copy service.sh
#      template: src=/opt/dtstack/ansible/super.sh.j2 dest=/app/{{packer}}/super.sh mode='0755'
#
##    - name: yum install supervisor
##      yum: name=supervisor state=latest
#
#    - name: copy supervisor.conf
#      template: src=/opt/dtstack/ansible/supervisor.conf.j2 dest=/app/{{packer}}/supervisor.conf mode='0755'
#
#    - name: stop service
#      shell: "bash /app/{{packer}}/super.sh stop"
#
#    - name: start service
#      shell: "bash /app/{{packer}}/super.sh start"
